version: "3.8"

services:
  # POSTGRES_DB_SERVICE
  postgres:
    container_name: database-ignite2
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: 2813
      POSTGRES_USER: postgres
      POSTGRES_DB: track_micro
      # POSTGRES_MULTIPLE_DATABASES: track_micro,auth_micro
    ports:
      - 5432:5432
    volumes:
      - pgdata:/data/postgres
      # - ./docker_postgres_init.sql:/docker-entrypoint initdb.d/docker_postgres_init.sql
    networks:
      - webnet

volumes:
  pgdata:
networks:
  webnet:
    driver: bridge
    name: webnet
