version: '3.8'
services:
  # AUTH MICROSERVICE
  nest-auth:
    container_name: AUTH-MICROSERVICE
    build:
      context: .
      dockerfile: Dockerfile
    image: music-auth
    ports:
      - 5000:5000
    networks:
      - webnet
    volumes:
      - .:/src
    env_file: .env
    depends_on:
      - postgres

  postgres:
    container_name: database-ignite
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: 2813
      POSTGRES_USER: postgres
      POSTGRES_DB: auth_micro
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/data/postgres
    networks:
      - webnet

volumes:
  pgdata:
networks:
  webnet:
#     external:
#       name: webnet
